# Generated by Django 5.2.17 on 2026-09-23 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Canonical E.164 form from Twilio Lookup', max_length=32)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('placed', 'Order placed'), ('dispatched', 'Order dispatched'), ('cancelled', 'Order cancelled'), ('delivery_followup', 'Delivery follow-up'), ('resend', 'Operator resend')], max_length=32)),
                ('recipient', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True, null=True)),
                ('provider_sid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('twilio_status', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('partial', 'Partially delivered'), ('unknown', 'Unknown')], default='pending', max_length=16)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('content_redacted', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contact_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='smsnotify.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resent_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resends', to='smsnotify.notification')),
            ],
            options={
                'ordering': ('created', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(fields=('owner', 'phone_number'), name='uniq_owner_phone_number'),
        ),
    ]
