# Generated by Django 5.2.17 on 2026-09-27 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        ('payment', '0005_auto_20200801_0817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=190, unique=True)),
                ('kind', models.CharField(choices=[('authorize', 'Authorize'), ('reauthorize', 'Reauthorize'), ('capture', 'Capture'), ('void', 'Void'), ('refund', 'Refund'), ('vault_create', 'Save card'), ('vault_delete', 'Delete saved card')], max_length=32)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('fingerprint', models.CharField(blank=True, max_length=128)),
                ('invoice_id', models.CharField(blank=True, max_length=127)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('provider_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('reserved_minor', models.BigIntegerField(default=0)),
                ('applied', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paypal_operations', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['order', 'kind'], name='paypal_api__order_i_cb82ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('cancelled', 'Cancelled before payment'), ('awaiting_payment', 'Awaiting payment'), ('authorized', 'Authorized'), ('capturing', 'Capturing'), ('captured', 'Captured'), ('voiding', 'Voiding'), ('voided', 'Voided'), ('authorization_expired', 'Authorization expired')], default='awaiting_payment', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('amount_minor', models.BigIntegerField()),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_created_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('original_authorization_id', models.CharField(blank=True, max_length=64)),
                ('reauthorized_at', models.DateTimeField(blank=True, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=32)),
                ('card_last_digits', models.CharField(blank=True, max_length=4)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_minor', models.BigIntegerField(default=0)),
                ('paypal_fee_minor', models.BigIntegerField(blank=True, null=True)),
                ('net_minor', models.BigIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reserved_minor', models.BigIntegerField(default=0)),
                ('refunded_minor', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paypal_payment', to='order.order')),
                ('saved_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.bankcard')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_payment', to='payment.source')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('refund_reserved_minor__lte', models.F('captured_minor'))), name='paypal_refunds_within_capture')],
            },
        ),
    ]
