# Generated by Django 5.2.17 on 2026-09-23 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='awaiting_payment', max_length=32)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255)),
                ('authorization_id', models.CharField(blank=True, max_length=255)),
                ('auth_status', models.CharField(blank=True, max_length=64)),
                ('auth_expiry', models.CharField(blank=True, max_length=64)),
                ('capture_id', models.CharField(blank=True, max_length=255)),
                ('capture_status', models.CharField(blank=True, max_length=64)),
                ('captured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paypal_event_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_vault_id', models.CharField(max_length=255, unique=True)),
                ('paypal_customer_id', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=64)),
                ('last_digits', models.CharField(blank=True, max_length=8)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('cardholder_name', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_customer_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='paypal_api.orderpayment')),
            ],
            options={
                'ordering': ['created'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='uniq_refund_idempotency_key_per_payment')],
            },
        ),
    ]
