# Generated by Django 5.2.17 on 2026-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='pay_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
