# Generated by Django 5.2.17 on 2026-09-23 20:01

import apps.maxio_billing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.maxio_billing.models.new_customer_reference, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('linked', 'Linked'), ('unknown', 'Unknown'), ('failed', 'Failed')], default='sending', max_length=16)),
                ('maxio_customer_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maxio_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maxio customer',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_handle', models.CharField(max_length=255)),
                ('reference', models.CharField(default=apps.maxio_billing.models.new_subscription_reference, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('active', 'Active'), ('pending', 'Pending'), ('attention', 'Needs attention'), ('needs_review', 'Needs review'), ('unknown', 'Unknown'), ('failed', 'Failed'), ('ended', 'Ended')], default='sending', max_length=16)),
                ('failure_reason', models.TextField(blank=True)),
                ('maxio_subscription_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('price_in_cents', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='maxio_billing.billingcustomer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maxio_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maxio subscription enrollment',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['failed', 'ended']), _negated=True), fields=('user', 'plan_handle'), name='maxio_one_live_enrollment_per_plan')],
            },
        ),
    ]
