# Generated by Django 5.2.17 on 2026-09-27 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_id', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('customer', 'Customer'), ('subscription', 'Subscription')], max_length=32)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=32)),
                ('plan_handle', models.CharField(blank=True, default='', max_length=255)),
                ('expected_price_in_cents', models.BigIntegerField(blank=True, null=True)),
                ('provider_id', models.CharField(blank=True, default='', max_length=64)),
                ('provider_state', models.CharField(blank=True, default='', max_length=64)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('detail', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_writes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
                'indexes': [models.Index(fields=['user', 'kind'], name='maxio_billi_user_id_d327fc_idx')],
            },
        ),
    ]
