# Generated by Django 5.2.17 on 2026-09-23 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e164', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('owner', 'e164')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_placed', 'Order placed'), ('order_dispatched', 'Order dispatched'), ('delivery_followup', 'Delivery follow-up'), ('order_cancelled', 'Order cancelled'), ('resend', 'Operator resend')], max_length=32)),
                ('to_number', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True, default='')),
                ('content_disposed', models.BooleanField(default=False)),
                ('provider_sid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('provider_status', models.CharField(blank=True, default='', max_length=32)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('partial', 'Partially delivered'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('unknown', 'Unknown')], default='pending', max_length=16)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('outcome_unknown', models.BooleanField(default=False)),
                ('provider_date_sent', models.DateTimeField(blank=True, null=True)),
                ('provider_date_created', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
                ('source_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resends', to='sms.notification')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('source_notification', 'idempotency_key'), name='uniq_resend_idempotency_key')],
            },
        ),
        migrations.CreateModel(
            name='OrderTransitionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_transition_claims', to='order.order')),
            ],
            options={
                'unique_together': {('order', 'to_status')},
            },
        ),
    ]
