# Generated by Django 5.2.17 on 2026-09-28 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        ('payment', '0005_auto_20200801_0817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='awaiting_payment', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('card_label', models.CharField(blank=True, max_length=64)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_created_at', models.DateTimeField(blank=True, null=True)),
                ('original_authorization_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reauthorized', models.BooleanField(default=False)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payment.bankcard')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_payment', to='payment.source')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=190, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('outcome', models.CharField(db_index=True, default='sending', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('request_fingerprint', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('provider_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('claimed_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paypal_writes', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
