# Generated by Django 5.2.17 on 2026-09-28 05:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        ('payment', '0005_auto_20200801_0817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='install', max_length=16, unique=True)),
                ('prefix', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('operation', models.CharField(max_length=32)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending at PayPal'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Outcome unknown')], default='sending', max_length=16)),
                ('provider_id', models.CharField(blank=True, max_length=64)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('claimed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['outcome', 'claimed_at'], name='payments_ap_outcome_abf48d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paypal_token_id', models.CharField(max_length=64, unique=True)),
                ('vault_customer_id', models.CharField(blank=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('awaiting_payment', 'awaiting_payment'), ('authorization_pending', 'authorization_pending'), ('authorized', 'authorized'), ('capture_pending', 'capture_pending'), ('captured', 'captured'), ('voided', 'voided'), ('cancelled', 'cancelled'), ('needs_review', 'needs_review'), ('outcome_unknown', 'outcome_unknown')], default='awaiting_payment', max_length=32)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('card_brand', models.CharField(blank=True, max_length=32)),
                ('card_last_digits', models.CharField(blank=True, max_length=4)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reserved', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.source')),
                ('saved_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments_api.savedcard')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending at PayPal'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Outcome unknown')], default='sending', max_length=16)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=64)),
                ('paypal_status', models.CharField(blank=True, max_length=32)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments_api.paypalpayment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='paypal_refund_key_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='paypalpayment',
            constraint=models.CheckConstraint(condition=models.Q(('refund_reserved__lte', models.F('captured_amount'))), name='paypal_refund_reserved_within_captured'),
        ),
    ]
