# Generated by Django 5.2.17 on 2026-09-23 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('authorized', 'Authorized (funds held)'), ('captured', 'Captured (funds taken)'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('voided', 'Voided (hold released)'), ('failed', 'Failed'), ('needs_review', 'Needs review')], default='awaiting_payment', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_expiry', models.DateTimeField(blank=True, null=True)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_token_id', models.CharField(max_length=64)),
                ('paypal_customer_id', models.CharField(blank=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('refund_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='paypal_checkout.paypalpayment')),
            ],
            options={
                'ordering': ['created'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='uniq_refund_idempotency_key')],
            },
        ),
    ]
