# Generated by Django 5.2.17 on 2026-09-22 10:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_customer_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('authorized', 'Authorized (funds held)'), ('captured', 'Captured (funds taken)'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Fully refunded'), ('cancelled', 'Cancelled (authorization voided)'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('currency', models.CharField(max_length=12)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('authorized_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paypal_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('request_id_base', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_vault_id', models.CharField(max_length=128, unique=True)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('cardholder_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=12)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='paypal_checkout.paypalpayment')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('payment', 'idempotency_key')},
            },
        ),
    ]
