# Generated by Django 5.2.17 on 2026-09-23 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        ('payment', '0005_auto_20200801_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting payment'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='AWAITING_PAYMENT', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_expiry', models.DateTimeField(blank=True, null=True)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('authorize_request_id', models.CharField(blank=True, max_length=64)),
                ('capture_request_id', models.CharField(blank=True, max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bankcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_payments', to='payment.bankcard')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='paypal_checkout.paypalpayment')),
            ],
            options={
                'ordering': ['date_created'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='uniq_refund_idempotency_per_payment')],
            },
        ),
    ]
