# Generated by Django 5.2.17 on 2026-09-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='paypal_invoice_id',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
