# Generated by Django 5.2.17 on 2026-09-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('national_format', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_placed', 'Order placed'), ('dispatched', 'Dispatched'), ('delivery_followup', 'Delivery follow-up'), ('cancelled', 'Cancelled')], max_length=32)),
                ('state', models.CharField(choices=[('pending', 'Claimed, not yet handed to the provider'), ('submitted', 'Accepted by the provider'), ('unknown', "Sent, but the provider's answer was lost"), ('send_failed', 'Not accepted by the provider'), ('skipped', 'Not sent (no number on file, or no longer wanted)')], default='pending', max_length=16)),
                ('to_number', models.CharField(blank=True, max_length=32)),
                ('body', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('provider_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('provider_error_code', models.IntegerField(blank=True, null=True)),
                ('provider_date_created', models.DateTimeField(blank=True, null=True)),
                ('provider_date_sent', models.DateTimeField(blank=True, null=True)),
                ('provider_checked_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('attempt_started_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_state', models.CharField(blank=True, choices=[('', 'Not requested'), ('requested', 'In progress'), ('done', 'Done'), ('unknown', 'Outcome unknown, will be re-checked'), ('failed', 'Failed, can be retried'), ('too_late', 'Message had already been sent'), ('not_needed', 'Nothing at the provider to act on')], default='', max_length=16)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('disposal_state', models.CharField(blank=True, choices=[('', 'Not requested'), ('requested', 'In progress'), ('done', 'Done'), ('unknown', 'Outcome unknown, will be re-checked'), ('failed', 'Failed, can be retried'), ('too_late', 'Message had already been sent'), ('not_needed', 'Nothing at the provider to act on')], default='', max_length=16)),
                ('disposal_requested_at', models.DateTimeField(blank=True, null=True)),
                ('content_disposed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='sms_notifications.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resends', to='sms_notifications.notification')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(fields=('user', 'phone_number'), name='sms_contact_number_unique_per_user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['provider_date_sent'], name='sms_notific_provide_33df03_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('resend_of__isnull', True)), fields=('order', 'kind'), name='sms_notification_one_per_order_kind'),
        ),
    ]
