# Generated by Django 5.2.17 on 2026-09-24 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_placed', 'Order placed'), ('order_dispatched', 'Order dispatched'), ('delivery_followup', 'Delivery follow-up'), ('order_cancelled', 'Order cancelled')], max_length=32)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('ref_token', models.CharField(max_length=16, unique=True)),
                ('body', models.TextField(blank=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('provider_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('provider_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_state', models.CharField(blank=True, max_length=16)),
                ('content_disposed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='sms_notifications.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resends', to='sms_notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'phone_number'), name='sms_contact_unique_active_number_per_user'),
        ),
    ]
