# Generated by Django 5.2.17 on 2026-09-28 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('placed', 'Order placed'), ('dispatched', 'Order dispatched'), ('follow_up', 'Delivery follow-up'), ('cancelled', 'Order cancelled')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('content_disposed_at', models.DateTimeField(blank=True, null=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('claimed_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('provider_error_code', models.IntegerField(blank=True, null=True)),
                ('provider_error_message', models.CharField(blank=True, max_length=255)),
                ('provider_date_created', models.DateTimeField(blank=True, null=True)),
                ('provider_date_sent', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_checked_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='sms_notifications.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resends', to='sms_notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProviderAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('action', models.CharField(choices=[('cancel', 'Cancel scheduled message'), ('redact', 'Redact content')], max_length=16)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('claimed_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_sid', models.CharField(blank=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sms_notifications.notification')),
            ],
            options={
                'ordering': ('claimed_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('user', 'phone_number'), name='sms_contact_number_unique_active'),
        ),
    ]
