"""Tests for the order SMS notification app.

Twilio is faked at the SDK's transport seam (a stub ``HttpClient``), so the real
request-building/decoding pipeline runs but no network call happens. No live
Twilio traffic is generated by this suite.
"""

import json
from decimal import Decimal as D

from django.contrib.auth import get_user_model
from django.test import TestCase, override_settings
from django.urls import reverse

from oscar.apps.catalogue.models import Product, ProductClass
from oscar.apps.partner.models import Partner, StockRecord

from twilio_sdk import Client
from twilio_sdk.core import BasicAuthCredentials, HttpRequest, HttpResponse

from . import twilio_gateway
from .models import ContactNumber, OrderNotification


# --- SDK transport stub --------------------------------------------------

class StubTransport:
    """Satisfies the SDK's sync transport protocol: send() + close()."""

    def __init__(self, *responses):
        self._responses = list(responses)
        self.requests = []

    def send(self, request):
        self.requests.append(request)
        if not self._responses:
            raise AssertionError("stub transport ran out of queued responses")
        return self._responses.pop(0)

    def close(self):
        pass

    @property
    def last_request(self):
        return self.requests[-1] if self.requests else None


class BoomTransport:
    def send(self, request):
        import httpx

        raise httpx.ConnectError("refused")

    def close(self):
        pass


def json_response(status, body):
    return HttpResponse(
        status_code=status,
        headers={"content-type": "application/json"},
        content=json.dumps(body).encode(),
    )


def _message_body(sid="SM123", status="queued", **extra):
    body = {
        "sid": sid,
        "status": status,
        "to": "+15551234567",
        "from": "+15550000000",
        "body": "hi",
        "date_sent": "Wed, 23 Sep 2026 12:00:00 +0000",
    }
    body.update(extra)
    return body


TEST_SETTINGS = dict(
    TWILIO_ACCOUNT_SID="AC00000000000000000000000000000000",
    TWILIO_AUTH_TOKEN="test-token",
    TWILIO_FROM_NUMBER="+15550000000",
    TWILIO_MESSAGING_SERVICE_SID="MG00000000000000000000000000000000",
    TWILIO_BASE_URL="",
)


@override_settings(**TEST_SETTINGS)
class SmsTestBase(TestCase):
    def install_stub(self, *responses):
        transport = StubTransport(*responses)
        twilio_gateway._client = Client(
            custom_http_client=transport,
            account_sid_auth_token=BasicAuthCredentials(
                username="x", password="y"
            ),
        )
        return transport

    def install_transport(self, transport):
        twilio_gateway._client = Client(
            custom_http_client=transport,
            account_sid_auth_token=BasicAuthCredentials(
                username="x", password="y"
            ),
        )
        return transport

    def tearDown(self):
        twilio_gateway._client = None

    def make_user(self, username="shopper", is_staff=False):
        User = get_user_model()
        return User.objects.create_user(
            username=username,
            email=f"{username}@example.com",
            password="password123",
            is_staff=is_staff,
        )

    def make_product(self, title="Widget", price="10.00"):
        pc, _ = ProductClass.objects.get_or_create(
            name="Default",
            defaults={"track_stock": False, "requires_shipping": False},
        )
        product = Product.objects.create(
            product_class=pc, title=title, structure=Product.STANDALONE
        )
        partner, _ = Partner.objects.get_or_create(name="Partner")
        StockRecord.objects.create(
            product=product,
            partner=partner,
            partner_sku=f"sku-{product.pk}",
            price=D(price),
            num_in_stock=100,
        )
        return product


# --- Gateway: number validation -----------------------------------------

class CanonicalizeTests(SmsTestBase):
    def test_returns_canonical_e164(self):
        self.install_stub(
            json_response(200, {"phone_number": "+15551234567", "country_code": "CA"})
        )
        assert twilio_gateway.canonicalize_number("(555) 123-4567") == "+15551234567"

    def test_rejects_unusable_number(self):
        self.install_stub(json_response(404, {"code": 20404, "message": "not found"}))
        with self.assertRaises(twilio_gateway.TwilioError) as ctx:
            twilio_gateway.canonicalize_number("+1555")
        assert ctx.exception.status_code == 404

    def test_decode_failure_is_outcome_unknown(self):
        # A 2xx whose body is the wrong shape -> ValidationError, not ApiError.
        self.install_stub(json_response(200, {"phone_number": ["not", "a", "string"]}))
        with self.assertRaises(twilio_gateway.TwilioError) as ctx:
            twilio_gateway.canonicalize_number("+15551234567")
        assert ctx.exception.outcome_unknown is True

    def test_transport_failure_is_outcome_unknown(self):
        self.install_transport(BoomTransport())
        with self.assertRaises(twilio_gateway.TwilioError) as ctx:
            twilio_gateway.canonicalize_number("+15551234567")
        assert ctx.exception.outcome_unknown is True


# --- Base-URL override ---------------------------------------------------

class BaseUrlOverrideTests(SmsTestBase):
    def test_override_hits_messaging_host_only(self):
        transport = StubTransport(
            json_response(201, _message_body()),
            json_response(200, {"phone_number": "+15551234567"}),
        )
        twilio_gateway._client = Client(
            custom_http_client=transport,
            account_sid_auth_token=BasicAuthCredentials(username="x", password="y"),
            server_config={"default": {"base_url": "https://example.test"}},
        )
        twilio_gateway.send_sms("+15551234567", "hi")
        assert transport.requests[0].url.startswith("https://example.test"), (
            transport.requests[0].url
        )
        # Lookups (server default4) must be untouched by the messaging override.
        twilio_gateway.canonicalize_number("+15551234567")
        assert transport.requests[1].url.startswith("https://lookups.twilio.com"), (
            transport.requests[1].url
        )


# --- Contact-number endpoints -------------------------------------------

class ContactNumberViewTests(SmsTestBase):
    def test_register_requires_auth(self):
        resp = self.client.post(
            reverse("sms:contact-numbers"),
            data=json.dumps({"number": "+15551234567"}),
            content_type="application/json",
        )
        assert resp.status_code == 401

    def test_register_and_list_and_scope(self):
        user = self.make_user()
        other = self.make_user("other")
        self.client.force_login(user)
        self.install_stub(json_response(200, {"phone_number": "+15551234567"}))
        resp = self.client.post(
            reverse("sms:contact-numbers"),
            data=json.dumps({"number": "(555) 123-4567"}),
            content_type="application/json",
        )
        assert resp.status_code == 201, resp.content
        cid = resp.json()["contactNumberId"]
        assert resp.json()["number"] == "+15551234567"

        # Owner sees it.
        resp = self.client.get(reverse("sms:contact-numbers"))
        assert len(resp.json()["contactNumbers"]) == 1

        # Another shopper cannot see or delete it.
        self.client.force_login(other)
        resp = self.client.get(reverse("sms:contact-numbers"))
        assert resp.json()["contactNumbers"] == []
        resp = self.client.delete(
            reverse("sms:contact-number-detail", args=[cid])
        )
        assert resp.status_code == 404
        assert ContactNumber.objects.filter(pk=cid).exists()

        # Owner deletes it.
        self.client.force_login(user)
        resp = self.client.delete(
            reverse("sms:contact-number-detail", args=[cid])
        )
        assert resp.status_code == 200
        assert not ContactNumber.objects.filter(pk=cid).exists()

    def test_register_rejects_unusable(self):
        user = self.make_user()
        self.client.force_login(user)
        self.install_stub(json_response(404, {"message": "not found"}))
        resp = self.client.post(
            reverse("sms:contact-numbers"),
            data=json.dumps({"number": "+1555"}),
            content_type="application/json",
        )
        assert resp.status_code == 422


# --- Order + notification flow ------------------------------------------

class OrderFlowTests(SmsTestBase):
    def _register_number(self, user):
        ContactNumber.objects.create(owner=user, e164="+15551234567")

    def test_place_order_sends_placed_sms(self):
        user = self.make_user()
        self._register_number(user)
        product = self.make_product()
        self.client.force_login(user)
        self.install_stub(json_response(201, _message_body(sid="SMplaced")))
        resp = self.client.post(
            reverse("sms:orders"),
            data=json.dumps({"items": [{"product_id": product.pk, "quantity": 2}]}),
            content_type="application/json",
        )
        assert resp.status_code == 201, resp.content
        data = resp.json()
        assert data["orderId"]
        assert data["notification"]["providerSid"] == "SMplaced"

    def test_place_order_without_number_is_not_messaged(self):
        user = self.make_user()
        product = self.make_product()
        self.client.force_login(user)
        # No stub responses queued: no Twilio call should happen.
        self.install_stub()
        resp = self.client.post(
            reverse("sms:orders"),
            data=json.dumps({"items": [{"product_id": product.pk, "quantity": 1}]}),
            content_type="application/json",
        )
        assert resp.status_code == 201, resp.content
        assert resp.json()["notification"] is None

    def test_send_failure_does_not_fail_order(self):
        user = self.make_user()
        self._register_number(user)
        product = self.make_product()
        self.client.force_login(user)
        # create_message -> 500 -> ApiError -> best effort
        self.install_stub(json_response(500, {"message": "boom"}))
        resp = self.client.post(
            reverse("sms:orders"),
            data=json.dumps({"items": [{"product_id": product.pk, "quantity": 1}]}),
            content_type="application/json",
        )
        assert resp.status_code == 201, resp.content
        notif = resp.json()["notification"]
        assert notif["status"] == OrderNotification.LOCAL_STATUS_SEND_FAILED
        assert notif["providerSid"] is None

    def _place_order(self, user, product):
        from . import services

        return services.place_order(user, [{"product_id": product.pk, "quantity": 1}])

    def test_dispatch_notifies_and_schedules_followup(self):
        user = self.make_user()
        self._register_number(user)
        operator = self.make_user("op", is_staff=True)
        product = self.make_product()
        order = self._place_order(user, product)
        self.client.force_login(operator)
        # dispatch immediate send, then scheduled follow-up.
        self.install_stub(
            json_response(201, _message_body(sid="SMdispatch", status="queued")),
            json_response(201, _message_body(sid="SMfollow", status="scheduled")),
        )
        resp = self.client.post(
            reverse("sms:order-dispatch", args=[order.pk])
        )
        assert resp.status_code == 200, resp.content
        data = resp.json()
        assert data["status"] == "Being processed"
        assert data["notification"]["providerSid"] == "SMdispatch"
        assert data["followup"]["providerSid"] == "SMfollow"
        assert data["followup"]["isScheduled"] is True

    def test_cancel_cancels_followup_and_notifies(self):
        user = self.make_user()
        self._register_number(user)
        operator = self.make_user("op", is_staff=True)
        product = self.make_product()
        order = self._place_order(user, product)
        # dispatch first (immediate + scheduled)
        self.client.force_login(operator)
        self.install_stub(
            json_response(201, _message_body(sid="SMdispatch")),
            json_response(201, _message_body(sid="SMfollow", status="scheduled")),
        )
        self.client.post(reverse("sms:order-dispatch", args=[order.pk]))

        # cancel: update_message(canceled) for follow-up, then cancel notice.
        self.install_stub(
            json_response(200, _message_body(sid="SMfollow", status="canceled")),
            json_response(201, _message_body(sid="SMcancel")),
        )
        resp = self.client.post(reverse("sms:order-cancel", args=[order.pk]))
        assert resp.status_code == 200, resp.content
        data = resp.json()
        assert data["status"] == "Cancelled"
        assert len(data["cancelledFollowups"]) == 1
        followup = OrderNotification.objects.get(provider_sid="SMfollow")
        assert followup.is_scheduled is False
        assert followup.status == "canceled"

    def test_dispatch_requires_staff(self):
        user = self.make_user()
        product = self.make_product()
        order = self._place_order(user, product)
        self.client.force_login(user)
        resp = self.client.post(reverse("sms:order-dispatch", args=[order.pk]))
        assert resp.status_code == 403

    def test_my_orders_scoped_to_caller(self):
        user = self.make_user()
        other = self.make_user("other")
        product = self.make_product()
        self._place_order(user, product)
        self.client.force_login(other)
        resp = self.client.get(reverse("sms:my-orders"))
        assert resp.json()["orders"] == []


# --- Resend / content / reconciliation ----------------------------------

class OperatorActionTests(SmsTestBase):
    def _make_order_with_failed_notif(self):
        user = self.make_user()
        contact = ContactNumber.objects.create(owner=user, e164="+15551234567")
        product = self.make_product()
        from . import services

        order = services.place_order(
            user, [{"product_id": product.pk, "quantity": 1}]
        )
        notif = OrderNotification.objects.create(
            order=order,
            recipient=contact,
            to_number=contact.e164,
            kind=OrderNotification.KIND_ORDER_PLACED,
            body="Your order was placed.",
            provider_sid="SMold",
            status="undelivered",
        )
        return user, order, notif

    def test_resend_is_idempotent(self):
        user, order, notif = self._make_order_with_failed_notif()
        operator = self.make_user("op", is_staff=True)
        self.client.force_login(operator)

        self.install_stub(json_response(201, _message_body(sid="SMresend1")))
        resp = self.client.post(
            reverse("sms:notification-resend", args=[notif.pk]),
            data=json.dumps({"idempotencyKey": "key-1"}),
            content_type="application/json",
        )
        assert resp.status_code == 201, resp.content
        first_id = resp.json()["notificationId"]
        assert resp.json()["created"] is True

        # Repeat under the SAME key: no second send (stub has no more responses).
        self.install_stub()
        resp = self.client.post(
            reverse("sms:notification-resend", args=[notif.pk]),
            data=json.dumps({"idempotencyKey": "key-1"}),
            content_type="application/json",
        )
        assert resp.status_code == 200, resp.content
        assert resp.json()["notificationId"] == first_id
        assert resp.json()["created"] is False

        # A fresh key sends again.
        self.install_stub(json_response(201, _message_body(sid="SMresend2")))
        resp = self.client.post(
            reverse("sms:notification-resend", args=[notif.pk]),
            data=json.dumps({"idempotencyKey": "key-2"}),
            content_type="application/json",
        )
        assert resp.status_code == 201, resp.content
        assert resp.json()["notificationId"] != first_id

    def test_resend_requires_staff(self):
        user, order, notif = self._make_order_with_failed_notif()
        self.client.force_login(user)
        resp = self.client.post(
            reverse("sms:notification-resend", args=[notif.pk]),
            data=json.dumps({"idempotencyKey": "k"}),
            content_type="application/json",
        )
        assert resp.status_code == 403

    def test_content_disposal_redacts(self):
        user, order, notif = self._make_order_with_failed_notif()
        self.client.force_login(user)
        self.install_stub(
            json_response(200, _message_body(sid="SMold", status="undelivered", body=""))
        )
        resp = self.client.delete(
            reverse("sms:notification-content", args=[notif.pk])
        )
        assert resp.status_code == 200, resp.content
        notif.refresh_from_db()
        assert notif.content_redacted is True
        assert notif.body == ""
        # the record of the send and its outcome survives
        assert notif.provider_sid == "SMold"
        assert notif.status == "undelivered"

    def test_reconciliation_lists_and_diffs(self):
        user, order, notif = self._make_order_with_failed_notif()
        operator = self.make_user("op", is_staff=True)
        self.client.force_login(operator)
        # provider returns SMold (matches app) and SMonlyprovider (app doesn't know)
        self.install_stub(
            json_response(
                200,
                {
                    "messages": [
                        _message_body(sid="SMold", status="undelivered"),
                        _message_body(sid="SMonlyprovider", status="delivered"),
                    ]
                },
            )
        )
        resp = self.client.get(
            reverse("sms:notification-reconciliation"),
            {"from": "2026-09-01T00:00:00Z", "to": "2026-12-31T00:00:00Z"},
        )
        assert resp.status_code == 200, resp.content
        data = resp.json()
        assert "SMold" in data["matched"]
        assert any(
            e["providerSid"] == "SMonlyprovider" for e in data["inProviderNotApp"]
        )

    def test_reconciliation_requires_staff(self):
        user = self.make_user()
        self.client.force_login(user)
        resp = self.client.get(
            reverse("sms:notification-reconciliation"),
            {"from": "2026-09-01T00:00:00Z", "to": "2026-12-31T00:00:00Z"},
        )
        assert resp.status_code == 403
