# Generated by Django 5.2.17 on 2026-09-23 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('placed', 'Order placed'), ('dispatched', 'Order dispatched'), ('cancelled', 'Order cancelled'), ('delivery_survey', 'Delivery survey (follow-up)'), ('resend', 'Operator re-send')], max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('provider_sid', models.CharField(blank=True, default='', max_length=64)),
                ('provider_status', models.CharField(blank=True, default='', max_length=32)),
                ('provider_error_code', models.IntegerField(blank=True, null=True)),
                ('provider_error_message', models.TextField(blank=True, default='')),
                ('provider_date_sent', models.DateTimeField(blank=True, null=True)),
                ('local_outcome', models.CharField(default='pending', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('is_followup', models.BooleanField(default=False)),
                ('scheduled_send_at', models.DateTimeField(blank=True, null=True)),
                ('followup_cancelled', models.BooleanField(default=False)),
                ('content_disposed', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resends', to='ordersms.ordernotification')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e164', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('user', 'e164')},
            },
        ),
    ]
