# Generated by Django 5.2.17 on 2026-09-23 00:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_customer_id', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('authorized', 'Authorized (funds held)'), ('captured', 'Captured (funds taken)'), ('voided', 'Voided (hold released)'), ('refunded', 'Refunded in full'), ('partially_refunded', 'Partially refunded')], default='awaiting_payment', max_length=32)),
                ('currency', models.CharField(max_length=12)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_expiry', models.DateTimeField(blank=True, null=True)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('authorize_request_id', models.CharField(blank=True, max_length=64)),
                ('capture_request_id', models.CharField(blank=True, max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_token_id', models.CharField(max_length=64, unique=True)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='api.paypalpayment')),
            ],
            options={
                'ordering': ['date_created'],
                'unique_together': {('payment', 'idempotency_key')},
            },
        ),
    ]
