# Generated by Django 5.2.17 on 2026-09-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='invoice_reference',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
