# Generated by Django 5.2.17 on 2026-09-29 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('national_format', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=32)),
                ('kind', models.CharField(choices=[('placed', 'Order placed'), ('dispatched', 'Order dispatched'), ('follow_up', 'Delivery follow-up'), ('cancelled', 'Order cancelled')], max_length=16)),
                ('trigger_key', models.CharField(max_length=191, unique=True)),
                ('body', models.TextField(blank=True)),
                ('reference_token', models.CharField(max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('provider_created_at', models.DateTimeField(blank=True, null=True)),
                ('provider_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('call_off_outcome', models.CharField(blank=True, choices=[('sending', 'Sending'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('unknown', 'Unknown')], max_length=16)),
                ('disposal_outcome', models.CharField(blank=True, choices=[('sending', 'Sending'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('unknown', 'Unknown')], max_length=16)),
                ('content_disposed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='order_notifications.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resends', to='order_notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProviderWrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=191, unique=True)),
                ('step', models.CharField(choices=[('send', 'Send'), ('cancel', 'Cancel'), ('redact', 'Redact')], max_length=16)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('provider_id', models.CharField(blank=True, max_length=64)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_writes', to='order_notifications.notification')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('disabled_at__isnull', True)), fields=('user', 'phone_number'), name='order_notifications_unique_active_number'),
        ),
    ]
