# Generated by Django 5.2.17 on 2026-09-30 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_placed', 'Order placed'), ('order_dispatched', 'Order dispatched'), ('delivery_follow_up', 'Delivery follow-up'), ('order_cancelled', 'Order cancelled')], max_length=32)),
                ('body', models.TextField(blank=True)),
                ('content_disposed_at', models.DateTimeField(blank=True, null=True)),
                ('send_state', models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('sent', 'sent'), ('rejected', 'rejected'), ('unknown', 'unknown'), ('suppressed', 'suppressed')], default='pending', max_length=16)),
                ('send_at', models.DateTimeField(blank=True, help_text='When Twilio is scheduled to send it (scheduled messages only).', null=True)),
                ('provider_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('from_number', models.CharField(blank=True, max_length=32)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('provider_date_sent', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_failed', models.BooleanField(default=False, help_text='A scheduled message could not be confirmed as called off.')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='order_notifications.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resends', to='order_notifications.notification')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(fields=('user', 'phone_number'), name='order_notifications_unique_number_per_user'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('resend_of__isnull', True)), fields=('order', 'kind'), name='order_notifications_one_lifecycle_message_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('resend_of', 'idempotency_key'), name='order_notifications_unique_resend_key'),
        ),
    ]
