# Generated by Django 5.2.17 on 2026-09-25 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('order_placed', 'Order placed'), ('order_dispatched', 'Order dispatched'), ('delivery_followup', 'Delivery follow-up'), ('order_cancelled', 'Order cancelled')], max_length=32)),
                ('body', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('outcome', models.CharField(choices=[('sending', 'sending'), ('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('unknown', 'unknown')], default='sending', max_length=16)),
                ('claimed_at', models.DateTimeField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('provider_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('provider_error_code', models.IntegerField(blank=True, null=True)),
                ('provider_error_message', models.CharField(blank=True, max_length=255)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_state', models.CharField(choices=[('none', 'none'), ('requested', 'requested'), ('done', 'done'), ('pending', 'pending'), ('too_late', 'too_late'), ('unknown', 'unknown')], default='none', max_length=16)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('content_state', models.CharField(choices=[('retained', 'retained'), ('disposing', 'disposing'), ('disposed', 'disposed'), ('unknown', 'unknown')], default='retained', max_length=16)),
                ('content_disposed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='order_notifications.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resends', to='order_notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['claimed_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('user', 'phone_number'), name='uniq_active_contact_number_per_user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['outcome'], name='order_notif_outcome_005a80_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['provider_time'], name='order_notif_provide_e36576_idx'),
        ),
    ]
