# Generated by Django 5.2.17 on 2026-09-28 01:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        ('payment', '0005_auto_20200801_0817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=127, unique=True)),
                ('kind', models.CharField(choices=[('authorize', 'Authorize'), ('reauthorize', 'Reauthorize'), ('capture', 'Capture'), ('void', 'Void'), ('refund', 'Refund'), ('vault_create', 'Save card'), ('vault_delete', 'Delete card')], max_length=32)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('provider_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('claimed_at', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('authorizing', 'Authorizing'), ('authorization_pending', 'Authorization pending'), ('authorized', 'Authorized'), ('reauthorizing', 'Reauthorizing'), ('capturing', 'Capturing'), ('capture_pending', 'Capture pending'), ('captured', 'Captured'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('voiding', 'Voiding'), ('voided', 'Voided'), ('needs_review', 'Needs review')], default='awaiting_payment', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=12)),
                ('authorize_attempt', models.PositiveIntegerField(default=1)),
                ('card_label', models.CharField(blank=True, max_length=64)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_created_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('original_authorization_id', models.CharField(blank=True, max_length=64)),
                ('reauthorized_at', models.DateTimeField(blank=True, null=True)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bankcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.bankcard')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.source')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=64)),
                ('paypal_status', models.CharField(blank=True, max_length=32)),
                ('reserved', models.BooleanField(default=True)),
                ('recorded', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='shop_payments.paypalpayment')),
                ('write', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shop_payments.paymentwrite')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentwrite',
            index=models.Index(fields=['kind', 'outcome'], name='shop_paymen_kind_b67f17_idx'),
        ),
        migrations.AddConstraint(
            model_name='paypalrefund',
            constraint=models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='uniq_refund_key_per_payment'),
        ),
    ]
