# Generated by Django 5.2.17 on 2026-09-29 01:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        ('payment', '0005_auto_20200801_0817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('provider_id', models.CharField(blank=True, max_length=128)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('provider_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('claimed_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_customer_id', models.CharField(blank=True, max_length=64)),
                ('times_deleted', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ref', models.CharField(max_length=200, unique=True)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('paypal_token_id', models.CharField(blank=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_outcome', models.CharField(blank=True, choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('unknown', 'Unknown')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('authorizing', 'Authorizing'), ('authorized', 'Authorized'), ('payment_failed', 'Payment Failed'), ('capturing', 'Capturing'), ('capture_pending', 'Capture Pending'), ('captured', 'Captured'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('needs_review', 'Needs Review')], default='awaiting_payment', max_length=32)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('card_label', models.CharField(blank=True, max_length=64)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('paypal_order_status', models.CharField(blank=True, max_length=32)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('honor_period_start', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reauthorizations', models.PositiveIntegerField(default=0)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_payment', to='payment.source')),
                ('saved_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sandbox_payments.savedcard')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('ref', models.CharField(max_length=200, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=64)),
                ('paypal_status', models.CharField(blank=True, max_length=32)),
                ('booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sandbox_payments.orderpayment')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='unique_refund_key_per_payment')],
            },
        ),
    ]
