# Generated by Django 5.2.17 on 2026-09-23 11:35

import apps.payments.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_customer_id', models.CharField(max_length=64, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.payments.models._new_reference, editable=False, max_length=32, unique=True)),
                ('state', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('authorizing', 'Authorizing'), ('authorization_unknown', 'Authorization outcome unknown'), ('authorized', 'Authorized (funds held)'), ('authorization_pending', 'Authorization pending at PayPal'), ('authorization_failed', 'Authorization declined'), ('authorization_expired', 'Authorization expired'), ('capturing', 'Capturing'), ('capture_unknown', 'Capture outcome unknown'), ('capture_pending', 'Capture pending at PayPal'), ('capture_failed', 'Capture declined'), ('captured', 'Captured'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('voiding', 'Releasing hold'), ('void_unknown', 'Release outcome unknown'), ('voided', 'Hold released'), ('cancelled', 'Cancelled before payment'), ('needs_review', 'Needs review')], default='awaiting_payment', max_length=32)),
                ('state_changed_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('card_brand', models.CharField(blank=True, max_length=32)),
                ('card_last_digits', models.CharField(blank=True, max_length=4)),
                ('paypal_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_created_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reauthorized', models.BooleanField(default=False)),
                ('capture_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('refund_reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('last_error', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('authorization', 'Authorization'), ('capture', 'Capture'), ('refund', 'Refund')], max_length=16)),
                ('paypal_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('provider_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_transactions', to='payments.paypalpayment')),
            ],
            options={
                'ordering': ['provider_time'],
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_key', models.CharField(max_length=100)),
                ('vault_token_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('cardholder_name', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('saving', 'Saving'), ('active', 'Active'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('failed', 'Failed'), ('unknown', 'Outcome unknown')], default='saving', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='saved_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.savedcard'),
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('completed', 'Completed'), ('pending', 'Pending at PayPal'), ('failed', 'Failed'), ('unknown', 'Outcome unknown')], default='sending', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('status_changed_at', models.DateTimeField()),
                ('paypal_refund_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('paypal_status', models.CharField(blank=True, max_length=32)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paypalpayment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='payments_refund_idempotency_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedcard',
            constraint=models.UniqueConstraint(fields=('user', 'request_key'), name='payments_savedcard_user_request_key'),
        ),
    ]
