# Generated by Django 5.2.17 on 2026-09-23 07:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        ('payment', '0005_auto_20200801_0817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_customer_id', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_key', models.CharField(max_length=128)),
                ('state', models.CharField(db_index=True, default='creating', max_length=16)),
                ('paypal_token_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('paypal_customer_id', models.CharField(blank=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(db_index=True, default='creating', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('card_label', models.CharField(blank=True, max_length=64)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('paypal_order_status', models.CharField(blank=True, max_length=32)),
                ('authorization_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_time', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires', models.DateTimeField(blank=True, null=True)),
                ('reauthorization_count', models.PositiveIntegerField(default=0)),
                ('capture_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('capture_time', models.DateTimeField(blank=True, null=True)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('refund_reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payments', to='order.order')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payment.source')),
                ('saved_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.savedcard')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequestKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='payments_orderkey_user_key')],
            },
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(db_index=True, default='sending', max_length=16)),
                ('paypal_refund_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('paypal_status', models.CharField(blank=True, max_length=32)),
                ('refund_time', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paypalpayment')),
            ],
            options={
                'ordering': ['date_created'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='payments_refund_idempotency')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedcard',
            constraint=models.UniqueConstraint(fields=('user', 'client_key'), name='payments_savedcard_user_key'),
        ),
        migrations.AddConstraint(
            model_name='paypalpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'failed'), _negated=True), fields=('order',), name='payments_one_live_payment_per_order'),
        ),
        migrations.AddConstraint(
            model_name='paypalpayment',
            constraint=models.UniqueConstraint(fields=('order', 'attempt'), name='payments_payment_order_attempt'),
        ),
    ]
