# Generated by Django 5.2.17 on 2026-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=24, unique=True)),
            ],
        ),
    ]
