# Generated by Django 5.2.17 on 2026-09-23 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('placed', 'Order placed'), ('dispatched', 'Order dispatched'), ('dispatched_followup', 'Delivery follow-up'), ('cancelled', 'Order cancelled'), ('resend', 'Operator resend')], max_length=32)),
                ('to_number', models.CharField(blank=True, max_length=32)),
                ('body', models.TextField(blank=True, default='')),
                ('provider_sid', models.CharField(blank=True, default='', max_length=64)),
                ('provider_status', models.CharField(blank=True, default='', max_length=32)),
                ('outcome', models.CharField(default='sending', max_length=16)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('is_followup', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('content_redacted', models.BooleanField(default=False)),
                ('scheduled_send_at', models.DateTimeField(blank=True, null=True)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_order_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_number', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'canonical_number'), name='uniq_user_contact_number')],
            },
        ),
        migrations.CreateModel(
            name='OrderTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_transitions', to='order.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'to_status'), name='uniq_order_transition')],
            },
        ),
    ]
