# Generated by Django 5.2.17 on 2026-09-24 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_placed', 'Order placed'), ('order_dispatched', 'Order dispatched'), ('delivery_followup', 'Delivery follow-up'), ('order_cancelled', 'Order cancelled'), ('resend', 'Operator re-send')], max_length=32)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64)),
                ('body', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('sending', 'sending'), ('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('unknown', 'unknown')], default='sending', max_length=16)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('message_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_detail', models.CharField(blank=True, max_length=255)),
                ('provider_date_created', models.DateTimeField(blank=True, null=True)),
                ('provider_date_sent', models.DateTimeField(blank=True, null=True)),
                ('cancel_outcome', models.CharField(blank=True, choices=[('requested', 'requested'), ('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('unknown', 'unknown')], max_length=16)),
                ('content_disposal', models.CharField(blank=True, choices=[('requested', 'requested'), ('pending', 'pending'), ('done', 'done'), ('failed', 'failed'), ('unknown', 'unknown')], max_length=16)),
                ('content_disposed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='order_sms.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resends', to='order_sms.notification')),
            ],
            options={
                'ordering': ['claimed_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'phone_number'), name='order_sms_one_active_number_per_user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['outcome'], name='order_sms_n_outcome_86968d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['provider_date_sent'], name='order_sms_n_provide_175c4c_idx'),
        ),
    ]
