# Generated by Django 5.2.17 on 2026-09-25 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e164', models.CharField(max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('placed', 'Order placed'), ('dispatched', 'Order dispatched'), ('followup', 'Delivery follow-up'), ('cancelled', 'Order cancelled')], max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('destination', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True)),
                ('content_disposed_at', models.DateTimeField(blank=True, null=True)),
                ('content_disposal_requested_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Delivered'), ('pending', 'In progress'), ('failed', 'Not delivered'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('provider_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('provider_error_code', models.IntegerField(blank=True, null=True)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_state', models.CharField(blank=True, choices=[('done', 'Called off'), ('pending', 'Cancel not confirmed yet'), ('failed', 'Too late to call off')], max_length=16)),
                ('contact_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='order_sms.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resends', to='order_sms.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['claimed_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'e164'), name='order_sms_one_active_number_per_user'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('resend_of', 'idempotency_key'), name='order_sms_one_resend_per_key'),
        ),
    ]
