# Generated by Django 5.2.17 on 2026-09-23 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_contact_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_placed', 'Order placed'), ('order_dispatched', 'Order dispatched'), ('delivery_followup', 'Delivery follow-up'), ('order_cancelled', 'Order cancelled')], max_length=32)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(default='claimed', max_length=32)),
                ('provider_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('provider_date_created', models.DateTimeField(blank=True, null=True)),
                ('provider_date_sent', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('content_redacted_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='order_sms.contactnumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='order.order')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resends', to='order_sms.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderTransitionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_transition_claims', to='order.order')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(fields=('user', 'phone_number'), name='order_sms_unique_user_number'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('resend_of__isnull', True)), fields=('order', 'kind'), name='order_sms_unique_event_message'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('resend_of__isnull', False)), fields=('resend_of', 'idempotency_key'), name='order_sms_unique_resend_key'),
        ),
        migrations.AddConstraint(
            model_name='ordertransitionclaim',
            constraint=models.UniqueConstraint(fields=('order', 'to_status'), name='order_sms_unique_transition'),
        ),
    ]
