# Generated by Django 5.2.17 on 2026-09-23 12:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0021_billingaddress_code_shippingaddress_code"),
        ("payment", "0005_auto_20200801_0817"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalCustomer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paypal_customer_id", models.CharField(max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_ref", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("saving", "Saving"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("unknown", "Unknown"),
                            ("deleting", "Deleting"),
                            ("deleted", "Deleted"),
                        ],
                        default="saving",
                        max_length=16,
                    ),
                ),
                (
                    "paypal_token_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("paypal_customer_id", models.CharField(blank=True, max_length=64)),
                ("brand", models.CharField(blank=True, max_length=32)),
                ("last_digits", models.CharField(blank=True, max_length=4)),
                ("expiry", models.CharField(blank=True, max_length=7)),
                ("holder_name", models.CharField(blank=True, max_length=255)),
                ("last_error", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_saved_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="PayPalPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "Awaiting Payment"),
                            ("authorizing", "Authorizing"),
                            ("authorization_pending", "Authorization Pending"),
                            ("authorization_unknown", "Authorization Unknown"),
                            ("authorized", "Authorized"),
                            ("payment_failed", "Payment Failed"),
                            ("capturing", "Capturing"),
                            ("capture_pending", "Capture Pending"),
                            ("capture_unknown", "Capture Unknown"),
                            ("captured", "Captured"),
                            ("voiding", "Voiding"),
                            ("void_unknown", "Void Unknown"),
                            ("voided", "Voided"),
                            ("cancelled", "Cancelled"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="awaiting_payment",
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("card_brand", models.CharField(blank=True, max_length=32)),
                ("card_last_digits", models.CharField(blank=True, max_length=4)),
                (
                    "paypal_order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("paypal_order_status", models.CharField(blank=True, max_length=32)),
                (
                    "authorization_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("authorization_status", models.CharField(blank=True, max_length=32)),
                (
                    "authorized_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("original_authorized_at", models.DateTimeField(blank=True, null=True)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authorization_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "previous_authorization_ids",
                    models.JSONField(blank=True, default=list),
                ),
                ("reauthorization_count", models.PositiveIntegerField(default=0)),
                (
                    "capture_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("capture_status", models.CharField(blank=True, max_length=32)),
                (
                    "captured_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "paypal_fee",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "refund_reserved",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paypal_payment",
                        to="order.order",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="payment.source",
                    ),
                ),
                (
                    "saved_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="paypal_payments.savedcard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayPalRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("sending", "Sending"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="sending",
                        max_length=16,
                    ),
                ),
                (
                    "paypal_refund_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("paypal_status", models.CharField(blank=True, max_length=32)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="paypal_payments.paypalpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["date_created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment", "idempotency_key"),
                        name="paypal_refund_unique_key",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="savedcard",
            constraint=models.UniqueConstraint(
                fields=("user", "request_ref"), name="saved_card_unique_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="paypalpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_reserved__gte", 0)),
                name="paypal_payment_refund_reserved_non_negative",
            ),
        ),
    ]
