# Generated by Django 5.2.17 on 2026-09-28 07:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_id', models.CharField(max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault_customer_id', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('operation', models.CharField(max_length=32)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('provider_id', models.CharField(blank=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('claimed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider_time'], name='paypal_paym_provide_50f3bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_id', models.CharField(max_length=64, unique=True)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('cardholder_name', models.CharField(blank=True, max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('authorization_pending', 'Authorization pending'), ('authorized', 'Authorized'), ('capture_pending', 'Capture pending'), ('captured', 'Captured'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('voided', 'Voided'), ('cancelled', 'Cancelled'), ('needs_review', 'Needs review')], default='awaiting_payment', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_attempt', models.PositiveIntegerField(default=1)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('card_brand', models.CharField(blank=True, max_length=32)),
                ('card_last_digits', models.CharField(blank=True, max_length=4)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paypal_payment', to='order.order')),
                ('saved_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='paypal_payments.savedcard')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key_hash', models.CharField(max_length=64)),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('needs_review', 'Needs review')], default='sending', max_length=16)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=64)),
                ('paypal_status', models.CharField(blank=True, max_length=32)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_held', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='paypal_payments.paypalpayment')),
            ],
            options={
                'ordering': ['created'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'key_hash'), name='uniq_refund_key_per_payment')],
            },
        ),
    ]
