# Generated by Django 5.2.17 on 2026-09-28 10:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True)),
                ('prefix', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=128, unique=True)),
                ('step', models.CharField(max_length=32)),
                ('outcome', models.CharField(choices=[('sending', 'sending'), ('done', 'done'), ('pending', 'pending'), ('failed', 'failed'), ('needs_review', 'needs_review'), ('unknown', 'unknown')], default='sending', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('provider_id', models.CharField(blank=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('provider_time', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_writes', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_writes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'active'), ('deleting', 'deleting'), ('deleted', 'deleted')], default='active', max_length=16)),
                ('paypal_token_id', models.CharField(max_length=64, unique=True)),
                ('paypal_customer_id', models.CharField(blank=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_digits', models.CharField(blank=True, max_length=4)),
                ('expiry', models.CharField(blank=True, max_length=7)),
                ('save_ref', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('awaiting_payment', 'awaiting_payment'), ('authorization_pending', 'authorization_pending'), ('authorized', 'authorized'), ('capture_pending', 'capture_pending'), ('captured', 'captured'), ('partially_refunded', 'partially_refunded'), ('refunded', 'refunded'), ('cancelled', 'cancelled'), ('needs_review', 'needs_review')], default='awaiting_payment', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('original_authorized_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reauthorized_at', models.DateTimeField(blank=True, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=32)),
                ('card_last_digits', models.CharField(blank=True, max_length=4)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='paypal_payments.savedcard')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('outcome', models.CharField(choices=[('sending', 'sending'), ('done', 'done'), ('pending', 'pending'), ('failed', 'failed'), ('needs_review', 'needs_review'), ('unknown', 'unknown')], default='sending', max_length=16)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='paypal_payments.orderpayment')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='paypal_refund_unique_key')],
            },
        ),
    ]
