# Generated by Django 5.2.17 on 2026-09-25 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('maxio_customer_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'billing customer',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_handle', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('pending', 'Pending'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('maxio_subscription_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('provider_state', models.CharField(blank=True, default='', max_length=64)),
                ('price_in_cents', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='subscriptions.billingcustomer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription enrollment',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('outcome__in', ['sending', 'done', 'pending', 'unknown', 'needs_review'])), fields=('user', 'plan_handle'), name='subscriptions_one_live_enrollment_per_plan')],
            },
        ),
    ]
