# Generated by Django 5.2.17 on 2026-09-24 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True, verbose_name='Maxio reference')),
                ('maxio_customer_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Maxio customer ID')),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing customer',
                'verbose_name_plural': 'Billing customers',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_handle', models.CharField(max_length=255, verbose_name='Plan handle')),
                ('sequence', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=255, unique=True, verbose_name='Maxio reference')),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('done', 'Done'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='sending', max_length=16)),
                ('maxio_subscription_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Maxio subscription ID')),
                ('provider_state', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription attempt',
                'verbose_name_plural': 'Subscription attempts',
                'ordering': ['-date_created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'plan_handle', 'sequence'), name='unique_subscription_attempt_sequence')],
            },
        ),
    ]
