# Generated by Django 5.2.17 on 2026-09-28 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_billingaddress_code_shippingaddress_code'),
        ('payment', '0005_auto_20200801_0817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('authorized', 'Authorized'), ('capture_pending', 'Capture pending'), ('captured', 'Captured'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='awaiting_payment', max_length=32)),
                ('authorize_attempt', models.PositiveIntegerField(default=1)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64)),
                ('authorization_id', models.CharField(blank=True, max_length=64)),
                ('authorization_status', models.CharField(blank=True, max_length=32)),
                ('authorization_created_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('capture_status', models.CharField(blank=True, max_length=32)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('paypal_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=32)),
                ('card_last_digits', models.CharField(blank=True, max_length=4)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal', to='payment.source')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderWrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ref', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('authorize', 'authorize'), ('reauthorize', 'reauthorize'), ('capture', 'capture'), ('void', 'void'), ('refund', 'refund'), ('vault_create', 'vault_create'), ('vault_delete', 'vault_delete')], max_length=16)),
                ('outcome', models.CharField(choices=[('sending', 'sending'), ('done', 'done'), ('pending', 'pending'), ('failed', 'failed'), ('needs_review', 'needs_review'), ('unknown', 'unknown')], default='sending', max_length=16)),
                ('bankcard_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('provider_id', models.CharField(blank=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('provider_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('claimed_at', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paypal_writes', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_writes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'outcome'], name='paypal_inte_kind_855174_idx')],
            },
        ),
    ]
